[build]
  command = "npm run build"  # or the build command specific to your project
  publish = "dist"  # Adjust to match your build output folder (e.g., 'build' for React, 'out' for Next.js)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
      Content-Encoding = "gzip"
